[package]
name = "cipher2"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }
dotenv = "0.15"
